var express = require('express');
var router = express.Router();

const itemList = [
  { id: 1, term: 'DevOps', definition: 'DevOps applies a set of tools, practices, and cultural philosophies to improve collaboration between development and operations teams within an organisation. Its primary goal is to break down silos between these traditionally separate functions and integrate the work and teams as much as possible to enhance the overall efficiency and effectiveness of the software development process.', references: 'AWS (2023) What is DevOps?, Amazon Web Service Inc., accessed 20 July 2023. https://aws.amazon.com/devops/what-is-devops/ and AXELOS (2015) PRINCE2 Agile®, 1st edn, United Kingdom.' },
  { id: 2, term: 'Waterfall', definition: 'The waterfall methodology uses a sequential or linear approach to software development, with distinct goals for each development phase. In this approach, development phases must be completed before moving onto the next, and previous phases cannot be revisited.', references: 'Sherman R (2015) ‘Project Management’, Business Intelligence Guidebook, pp.449-492. DOI: https://doi.org/10.1016/B978-0-12-411461-6.00018-6 and AXELOS (2018) Managing Successful Projects with PRINCE2, 6th edn, United Kingdom.' },
  { id: 3, term: 'Agile', definition: 'The Agile methodology describes a collection of behaviours, frameworks, concepts, and techniques that combine to support a more iterative, collaborative approach to software development. It emphasises adaptability, customer feedback, and delivering working software in short, incremental cycles (sprints). Scrum and Kanban are examples of specific Agile methods.', references: 'AXELOS (2018) Managing Successful Projects with PRINCE2, 6th edn, United Kingdom.' },
  { id: 4, term: 'Silos', definition: 'Organisational silos refer to the isolation of teams or entire departments from other parts of the business due to a lack of information and knowledge sharing. These barriers contribute to organisational inefficiencies including, duplicate work efforts, poor resource allocation, decreased productivity and ineffective decision-making processes.', references: 'Billingsley S (27 May 2021) Organisational Silos, LinkedIn, accessed 20 July 2021. https://www.linkedin.com/pulse/organizational-silos-scott-billingsley/' },
  { id: 5, term: 'CI/CD', definition: 'CI/CD falls under DevOps and combines the practice of continuous integration and continuous deployment. It applies a continuous and iterative build, test and deploy process through automation to streamline the development process, detect and fix issues early, and deliver software updates more frequently and reliably.', references: 'GitLab (2023) What is CI/CD, GitLab B.V., accessed 20 July 2023. https://about.gitlab.com/topics/ci-cd/' },
  { id: 6, term: 'Microservices', definition: 'Microservices represent an architectural and organisational approach to software development where software is composed of small, independent, and loosely coupled services that can be developed, deployed, and scaled independently. These services are owned by small, self-contained teams and promote agility, flexibility, and technological freedom.', references: 'AWS (2023) Microservices, Amazon Web Service Inc., accessed 20 July 2023. https://aws.amazon.com/microservices/' },
  { id: 7, term: 'Technical Debt', definition: 'Technical debt – or tech debt – refers to the implied costs of businesses taking shortcuts to expedite the delivery of functionality that will have a negative impact on them in the future.  Simply put, it is the result of prioritising delivery speed over perfect implementation (code).', references: 'Lutkevich B (Feb 2023) Technical Debt, TechTarget, accessed 21 July 2023. https://www.techtarget.com/whatis/definition/technical-debt' },
  { id: 8, term: 'Open-Source', definition: 'Open-source software refers to software that is publicly available for use, modification and distribution as users or developers see fit. It is developed and maintained via open collaboration, fostering transparency, customisation, and innovation.', references: 'IBM (n.d.) What isopen source software? [newsletter], IBM, accessed 21 July 2023. https://www.ibm.com/topics/open-source' },
  { id: 9, term: 'COTS', definition: 'In software development, COTS (Commercial Off the Shelf) refer to pre-built software applications or products that are available for sale, lease, or license to the general public. These applications and products are often developed by third-party vendors for organisations to implement or integrate.', references: 'NIST (n.d.) commercial-off-the-shf (COTS), Computer Security Resource Center (CSRS), accessed 21 July 2023. https://csrc.nist.gov/glossary/term/commercial_off_the_shelf' },
  { id: 10, term: 'Tool Ecosystems', definition: 'Tool ecosystems refer to the collection of software tools and technologies that combine to support the various stages of software development. In DevOps tool stacks assist individuals to operate and develop applications quickly. This increases productivity and delivery timeframes while reducing overall costs. ', references: 'Bangbit Technologies (9 Dec 2018) A comprehensive Guide to DevOps & It’s Tools Ecosystem, medium.com, accessed 20 July 2023. https://medium.com/@BangBitTech/a-comprehensive-guide-to-devops-its-tools-ecosystem-83d739cdf543' },
];


/* GET home page. */
router.get('/', function (req, res, next) {
  res.render('index', { title: 'SIT722 DevOps Glossary', sub: 'This glossary defines confusing terms associated with DevOps.', items: itemList });
});

module.exports = router;